// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGZD7DqqFMJKhrd-gTkr5NliNNJpUF0Us',
    appId: '1:566940734549:web:32907390fdea700893f0dc',
    messagingSenderId: '566940734549',
    projectId: 'portfolio-d1ba6',
    authDomain: 'portfolio-d1ba6.firebaseapp.com',
    storageBucket: 'portfolio-d1ba6.firebasestorage.app',
    measurementId: 'G-CTJMDXGYN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnqZx4pXWSueAwN71WrBkFt7uZajjCKJw',
    appId: '1:566940734549:android:e574aa28904b95ff93f0dc',
    messagingSenderId: '566940734549',
    projectId: 'portfolio-d1ba6',
    storageBucket: 'portfolio-d1ba6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAigF98TLrnrkPZkmw6EEtkmQEY1bReTCM',
    appId: '1:566940734549:ios:9fe6d9f047c88d9893f0dc',
    messagingSenderId: '566940734549',
    projectId: 'portfolio-d1ba6',
    storageBucket: 'portfolio-d1ba6.firebasestorage.app',
    iosBundleId: 'com.example.aiPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAigF98TLrnrkPZkmw6EEtkmQEY1bReTCM',
    appId: '1:566940734549:ios:9fe6d9f047c88d9893f0dc',
    messagingSenderId: '566940734549',
    projectId: 'portfolio-d1ba6',
    storageBucket: 'portfolio-d1ba6.firebasestorage.app',
    iosBundleId: 'com.example.aiPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGZD7DqqFMJKhrd-gTkr5NliNNJpUF0Us',
    appId: '1:566940734549:web:2b75233731ef342c93f0dc',
    messagingSenderId: '566940734549',
    projectId: 'portfolio-d1ba6',
    authDomain: 'portfolio-d1ba6.firebaseapp.com',
    storageBucket: 'portfolio-d1ba6.firebasestorage.app',
    measurementId: 'G-3K1QLYXZGV',
  );
}
